version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    hostname: go_template_postgres
    container_name: go_template_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: master
    ports:
      - "5432:5432"